server {
    listen 8080;
    server_name _;

    # Path inside your repo
    root ${HOME}/birdfeeder;

    location /streams/ {

        # CORS
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type" always;

        # MIME
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }

        # Playlists: must NOT be cached
        location ~ \.m3u8$ {
            add_header Cache-Control "no-store" always;
        }

        # Segments: small cache is fine (optional)
        location ~ \.ts$ {
            add_header Cache-Control "public, max-age=1, immutable" always;
        }

        autoindex off;
        try_files $uri =404;
    }

    location /api/battery {
        alias ${HOME}/birdfeeder/battery/battery_logs/latest_battery_data.csv;
        default_type text/csv;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Cache-Control "no-store" always;
    }
}